version: '3.4'

services:
  actions-runner:
    image: zerosuxx/github-actions-runner:latest
    build:
      context: .
    environment: 
      REPOSITORY: ${REPOSITORY}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
