version: '3.4'

services:
  actions-runner:
    image: zerosuxx/github-actions-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
