version: '3.4'

services:
  actions-runner:
    image: zerosuxx/github-actions-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /actions-runner/_build:/actions-runner/_build
    environment: 
      REPOSITORY: ${RUNNER_REPOSITORY_URL}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_WORKING_DIRECTORY: '_build'
